package org.consulo.python;

import com.intellij.psi.tree.TokenSet;

/**
 * @author VISTALL
 * @since 23.08.13.
 */
public interface PythonTokenSets extends PyTokenTypes {

	TokenSet KEYWORDS = TokenSet.create(AND_KEYWORD, ASSERT_KEYWORD, BREAK_KEYWORD, CLASS_KEYWORD, CONTINUE_KEYWORD, DEF_KEYWORD, DEL_KEYWORD, ELIF_KEYWORD, ELSE_KEYWORD, EXCEPT_KEYWORD, EXEC_KEYWORD, FINALLY_KEYWORD, FOR_KEYWORD, FROM_KEYWORD, GLOBAL_KEYWORD, IF_KEYWORD, IMPORT_KEYWORD, IN_KEYWORD, IS_KEYWORD, LAMBDA_KEYWORD, NOT_KEYWORD, OR_KEYWORD, PASS_KEYWORD, PRINT_KEYWORD, RAISE_KEYWORD, RETURN_KEYWORD, TRY_KEYWORD, WHILE_KEYWORD, YIELD_KEYWORD);
	TokenSet OPERATIONS = TokenSet.create(PLUS, MINUS, MULT, EXP, DIV, FLOORDIV, PERC, LTLT, GTGT, AND, OR, XOR, TILDE, LT, GT, LE, GE, EQEQ, NE, NE_OLD, AT, COLON, TICK, EQ, PLUSEQ, MINUSEQ, MULTEQ, DIVEQ, FLOORDIVEQ, PERCEQ, ANDEQ, OREQ, XOREQ, LTLTEQ, GTGTEQ, EXPEQ);

	TokenSet COMPARISON_OPERATIONS = TokenSet.create(LT, GT, EQEQ, GE, LE, NE, NE_OLD, IN_KEYWORD, IS_KEYWORD, NOT_KEYWORD);

	TokenSet SHIFT_OPERATIONS = TokenSet.create(LTLT, GTGT);
	TokenSet ADDITIVE_OPERATIONS = TokenSet.create(PLUS, MINUS);
	TokenSet MULTIPLICATIVE_OPERATIONS = TokenSet.create(MULT, FLOORDIV, DIV, PERC);
	TokenSet UNARY_OPERATIONS = TokenSet.create(PLUS, MINUS, TILDE);
	TokenSet END_OF_STATEMENT = TokenSet.create(STATEMENT_BREAK, SEMICOLON);
	TokenSet WHITESPACE = TokenSet.create(SPACE, TAB, FORMFEED);
	TokenSet WHITESPACE_OR_LINEBREAK = TokenSet.create(SPACE, TAB, FORMFEED, LINE_BREAK);
	TokenSet COMMENTS = TokenSet.create(PyTokenTypes.END_OF_LINE_COMMENT);
	TokenSet STRINGS = TokenSet.create(PyTokenTypes.STRING_LITERAL);
	TokenSet OPEN_BRACES = TokenSet.create(LBRACKET, LBRACE, LPAR);
	TokenSet CLOSE_BRACES = TokenSet.create(RBRACKET, RBRACE, RPAR);

	TokenSet AUG_ASSIGN_OPERATIONS = TokenSet.create(PLUSEQ, MINUSEQ, MULTEQ, DIVEQ, PERCEQ, EXPEQ, GTGTEQ, LTLTEQ, ANDEQ, OREQ, XOREQ);
}
